products/urls.py
from django.urls import path, re_path
from .views import (
    PostList,
    show_category,
    PostListView,
    PostCRUDView,
)

urlpatterns = [
    path("", PostList.as_view()),
    re_path(r"^category/(?P<hierarchy>.+)/$", show_category, name="category"),
    path(
        "api/v1/post/<slug:slug>/",
        PostCRUDView.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "delete": "destroy",
            }
        ),
    ),
    path(
        "api/v1/post/",
        PostListView.as_view(),
    ),
]

sunrise_store/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("products.urls")),
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.authtoken")),
]

urlpatterns += doc_urls
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Post(models.Model):
    created_at = models.DateTimeField(
        "Дата добавления",
        auto_now_add=True,
    )
    title = models.CharField(
        "Название товара",
        max_length=150,
    )
    slug = models.SlugField(
        "Слаг",
        unique=True,
        editable=True,
    )
    description = models.TextField(
        "Описание товара",
    )
    price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name="Цена",
    )
    image = models.ImageField(
        "Фотография товара",
        upload_to="product-image/%Y/%m/%d",
    )
    category = TreeForeignKey(
        "Category",
        null=True,
        blank=True,
        on_delete=CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products", args=[str(self.slug)])

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Category(MPTTModel):
    title = models.CharField("Название категории", max_length=150, unique=True)
    parent = TreeForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=CASCADE,
        related_name="children",
        db_index=True,
    )
    slug = models.SlugField("Слаг")

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except Exception:
            ancestors = []
        else:
            ancestors = [i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append("/".join(ancestors[: i + 1]))
        return slugs

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ["title"]

    class Meta:
        unique_together = (
            "parent",
            "slug",
        )
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Profile(AbstractUser):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        default=None,
        null=True,
        on_delete=models.CASCADE,
    )
    phone = models.CharField(
        max_length=20,
        verbose_name="Номер телефона",
        null=True,
        blank=True,
    )
    address = models.CharField(
        max_length=255,
        verbose_name="Адрес",
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

products/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.views.generic import View
from .models import (
    Category,
    Post,
)
from .serializers import (
    PostListSerializer,
    PostSerializer,
)
from rest_framework import permissions, generics
from .classes import CreateRetrieveUpdateDestroy


class PostList(View):
    def get(self, request: HttpResponse):
        category = Category.objects.all()
        post = Post.objects.all()

        return render(
            request,
            "products/index.html",
            {"category": category, "post": post},
        )


def show_category(request, hierarchy=None):
    category_slug = hierarchy.split("/")
    print(category_slug)
    parent = None
    root = Category.objects.all()

    for slug in category_slug[:-1]:
        parent = root.get(parent=parent, slug=slug)

    try:
        instance = Category.objects.get(parent=parent, slug=category_slug[-1])
    except Exception:
        instance = get_object_or_404(Post, slug=category_slug[-1])
        return render(
            request,
            "products/post_detail.html",
            {
                "instance": instance,
            },
        )
    else:
        return render(
            request,
            "products/categories.html",
            {
                "instance": instance,
            },
        )


class PostListView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    filter_fields = ("category__slug",)


class PostCRUDView(CreateRetrieveUpdateDestroy):

    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    lookup_field = "slug"
    permission_classes_by_action = {
        "get": [permissions.AllowAny],
        "update": [permissions.AllowAny],
        "destroy": [permissions.AllowAny],
    }

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/products/base.html
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block head_title %}
        {% endblock %}
    </title>
</head>

<body>
    <header>
        <li>
            {% if user.is_authenticated %}
            <span>{{ user.username }}</span>
            <a href="{% url 'account_logout' %}">
                Выход
            </a>
            {% else %}
            <a href="{% url 'account_login' %}">
                Вход
            </a>
            <a href="{% url 'account_signup' %}">
                Регистрация
            </a>
            {% endif %}
        </li>

    </header>
    {% block content %}
    {% endblock %}
</body>

</html>

templates/products/categories.html
{% extends 'products/base.html' %}
{% load static %}
{% comment %} {% load mptt_tags %} {% endcomment %}



{% block content %}

<h2>
  <li>
    <a href="/">Главная</a>
  </li>
</h2>



{% comment %} <ul>
    {% recursetree category %}
        <li>
            <a href="/category/{{ node.slug }}/">{{ node.title }}</a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    <a href="/category/{{ node.slug }}">{{ children }}</a>
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul> {% endcomment %}

<br>
<div class="text-center">
  <h2>{{instance.name}}</h2>
</div>



{% if instance.children.all %}
  <h4>Подкатегории</h4>
    <li>{{ instance }}</li>
    {% for i in instance.children.all %}
      <ul>  
        <li><a href="{{ i.slug }}"> {{ i.title }} </a><br></li>
      </ul>
      {% endfor %}

  <br>
  <hr>
{% endif %}

  {% if instance.post_set.all %}
    <h1>Товары</h1>
    {% for i in instance.post_set.all %}
    <h2>{{ i }}</h2>
    <div class="row small-up-1 medium-up-3">
      <div class="column">
        <a href="{{ i.slug }}">
          <div class="card" style="width: 300px; border-color: black">
            {% comment %} <div class="card-divider">
              <strong>{{ i.title | truncatechars:30}}</strong>
            </div> {% endcomment %}

            <img src="{{ i.image.url }}" height="200" , width="200">
            
            <p>Стоимость {{ i.price }}$<p>

            <div class="card-section">
              <small>{{ i.created_at}} </small>
              <p>{{ i.content | safe | truncatechars_html:120 }}</p>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
  {% else %}
      <h4>Пусто</h4>
  {% endif %}

    </div>
    {% endblock %}

templates/products/index.html
<!DOCTYPE html>
{% load mptt_tags %}


<head>
  <title>Online Store</title>
</head>

<body>
  <h1>
    Главная страница
  </h1>

  <header>
    <li>
      {% if user.is_authenticated %}
      <span>{{ user.username }}</span>
      <a href="{% url 'account_logout' %}">
        Выход
      </a>
      {% else %}
      <a href="{% url 'account_login' %}">
        Вход
      </a>
      <a href="{% url 'account_signup' %}">
        Регистрация
      </a>
      {% endif %}
    </li>

  </header>


  <ul>
    {% recursetree category %}
    <li>
      <a href="/category/{{ node.slug }}/">{{ node.title }}</a>
      {% if not node.is_leaf_node %}
      <ul class="children">
        <a href="/category/{{ node.slug }}">{{ children.slug }}</a>
      </ul>
      {% endif %}
    </li>
    {% endrecursetree %}
  </ul>

  {% if post %}
  <h1>Все товары</h1>
  {% for i in post %}
  <h2>{{ i }}</h2>
  <div class="row small-up-1 medium-up-3">
    <div class="column">
        <div class="card" style="width: 300px; border-color: black">
          {% comment %} <div class="card-divider">
            <strong>{{ i.title | truncatechars:30}}</strong>
          </div> {% endcomment %}

          <img src="{{ i.image.url }}" height="200" , width="200">

          <p>Стоимость {{ i.price }}$
          <p>

          <div class="card-section">
            <small>{{ i.created_at}} </small>
            <p>{{ i.content | safe | truncatechars_html:120 }}</p>
          </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h4>Пусто</h4>
    {% endif %}

</body>

templates/products/post_detail.html
{% comment %} {% load namify %} {% endcomment %}
<div>
    <li>
        <a href="/">Главная</a>
    </li>
</div>

<div class="breadcrumbs">
    <ul class="breadcrumbs">
        
        {% for i in instance.category.get_slug_list %}
                <li> 
                    <a href="/category/{{ i }}">{{ i }}</a>
                </li>
        {% endfor %}

        
    </ul> 
</div>
<br>

<div>
        <p>{{ instance.title }}<p>
        <img src="{{ instance.image.url }}" height="200" , width="200">
        <p>Описание: {{ instance.description }}<p>
        <p>Стоимость {{ instance.price }}$<p>
<div>